SHUTDOWN IMMEDIATE;
STARTUP UPGRADE;
ALTER SYSTEM SET max_string_size=EXTENDED scope=spfile;
START $ORACLE_HOME/rdbms/admin/utl32k.sql
SHUTDOWN IMMEDIATE;
STARTUP;
SHOW PARAMETER MAX_STRING_SIZE;
SELECT UTL_INADDR.get_host_address from dual;