alter session set "_oracle_script"=true;
-- DROP USER HID_GH_045 cascade;
CREATE USER  HID_GH_045 IDENTIFIED BY HID_GH_045 TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT CONNECT TO HID_GH_045;
GRANT CREATE SESSION TO HID_GH_045;
GRANT UNLIMITED TABLESPACE TO HID_GH_045;
GRANT RESOURCE TO HID_GH_045;

